export const BOOKMARK_LIST_SIZE = 15

export const BODY_TEXT_CHUNKS_SIZE = 1000

export const TAGS_SIZE = 50

export const MAX_BOOKMARK_SIZE = 200

export const TIMEOUT_URL_PARSER = 30000

export const BOOKMARK_CRON_SIZE = 1

/**
 * 기본 Bookmark fields
 */
export const BOOKMARK_FIELDS = [
  {
    label: 'ACCOUNTING',
    emoji: '💼',
    label_ko: '회계',
    label_en: 'Accounting',
  },
  {
    label: 'ADMINISTRATION',
    emoji: '🛠️',
    label_ko: '관리',
    label_en: 'Administration',
  },
  {
    label: 'ADVERTISING',
    emoji: '📢',
    label_ko: '광고',
    label_en: 'Advertising',
  },
  {
    label: 'ANALYTICS',
    emoji: '📊',
    label_ko: '분석',
    label_en: 'Analytics',
  },
  {
    label: 'ANIME',
    emoji: '👾',
    label_ko: '애니메이션',
    label_en: 'Anime',
  },
  {
    label: 'ARCHITECTURE',
    emoji: '🏛️',
    label_ko: '건축',
    label_en: 'Architecture',
  },
  {
    label: 'ARTIFICIAL_INTELLIGENCE',
    emoji: '🤖',
    label_ko: '인공지능',
    label_en: 'Artificial Intelligence',
  },
  {
    label: 'ARTS',
    emoji: '🎨',
    label_ko: '예술',
    label_en: 'Arts',
  },
  {
    label: 'BEAUTY',
    emoji: '💄',
    label_ko: '뷰티',
    label_en: 'Beauty',
  },
  {
    label: 'BLOCKCHAIN',
    emoji: '🔗',
    label_ko: '블록체인',
    label_en: 'Blockchain',
  },
  {
    label: 'BLOG',
    emoji: '📝',
    label_ko: '블로그',
    label_en: 'Blog',
  },
  {
    label: 'BOOKS',
    emoji: '📚',
    label_ko: '책',
    label_en: 'Books',
  },
  {
    label: 'BROWSERS',
    emoji: '🌐',
    label_ko: '브라우저',
    label_en: 'Browsers',
  },
  {
    label: 'BUSINESS',
    emoji: '🏢',
    label_ko: '비즈니스',
    label_en: 'Business',
  },
  {
    label: 'CAREER',
    emoji: '👔',
    label_ko: '직업',
    label_en: 'Career',
  },
  {
    label: 'CARS',
    emoji: '🚗',
    label_ko: '자동차',
    label_en: 'Cars',
  },
  {
    label: 'CLEANING',
    emoji: '🧹',
    label_ko: '청소',
    label_en: 'Cleaning',
  },
  {
    label: 'COMICS',
    emoji: '🦸',
    label_ko: '만화',
    label_en: 'Comics',
  },
  {
    label: 'COMMUNITY',
    emoji: '👥',
    label_ko: '커뮤니티',
    label_en: 'Community',
  },
  {
    label: 'COMPUTERS',
    emoji: '💻',
    label_ko: '컴퓨터',
    label_en: 'Computers',
  },
  {
    label: 'CONTENT_DISCOVERY',
    emoji: '🔍',
    label_ko: '콘텐츠 발견',
    label_en: 'Content Discovery',
  },
  {
    label: 'CREATIVE_AGENCY',
    emoji: '🎨',
    label_ko: '크리에이티브 에이전시',
    label_en: 'Creative Agency',
  },
  {
    label: 'CREATIVITY',
    emoji: '🎨',
    label_ko: '창의성',
    label_en: 'Creativity',
  },
  {
    label: 'CRYPTO',
    emoji: '₿',
    label_ko: '암호화폐',
    label_en: 'Crypto',
  },
  {
    label: 'CULTURE',
    emoji: '🎭',
    label_ko: '문화',
    label_en: 'Culture',
  },
  {
    label: 'DATABASE',
    emoji: '🗄️',
    label_ko: '데이터베이스',
    label_en: 'Database',
  },
  {
    label: 'DESIGN',
    emoji: '🎨',
    label_ko: '디자인',
    label_en: 'Design',
  },
  {
    label: 'DEVELOPMENT',
    emoji: '🚀',
    label_ko: '개발',
    label_en: 'Development',
  },
  {
    label: 'DEVOPS',
    emoji: '🔧',
    label_ko: '개발 운영',
    label_en: 'DevOps',
  },
  {
    label: 'DIY',
    emoji: '🛠️',
    label_ko: '자작',
    label_en: 'DIY',
  },
  {
    label: 'DOCUMENTARY',
    emoji: '🎥',
    label_ko: '다큐멘터리',
    label_en: 'Documentary',
  },
  {
    label: 'DOCUMENTATION',
    emoji: '📄',
    label_ko: '문서화',
    label_en: 'Documentation',
  },
  {
    label: 'DOWNLOADS',
    emoji: '⬇️',
    label_ko: '다운로드',
    label_en: 'Downloads',
  },
  {
    label: 'E-COMMERCE',
    emoji: '🛒',
    label_ko: '전자상거래',
    label_en: 'E-Commerce',
  },
  {
    label: 'EBOOKS',
    emoji: '📚',
    label_ko: '전자책',
    label_en: 'Ebooks',
  },
  {
    label: 'EDUCATION',
    emoji: '🎓',
    label_ko: '교육',
    label_en: 'Education',
  },
  {
    label: 'ELECTRONICS',
    emoji: '📱',
    label_ko: '전자기기',
    label_en: 'Electronics',
  },
  {
    label: 'ENGINEERING',
    emoji: '🔧',
    label_ko: '공학',
    label_en: 'Engineering',
  },
  {
    label: 'ENTERTAINMENT',
    emoji: '🎭',
    label_ko: '엔터테인먼트',
    label_en: 'Entertainment',
  },
  {
    label: 'ENVIRONMENT',
    emoji: '🌳',
    label_ko: '환경',
    label_en: 'Environment',
  },
  {
    label: 'EVENTS',
    emoji: '🎉',
    label_ko: '이벤트',
    label_en: 'Events',
  },
  {
    label: 'FASHION',
    emoji: '👗',
    label_ko: '패션',
    label_en: 'Fashion',
  },
  {
    label: 'FINANCE',
    emoji: '💰',
    label_ko: '금융',
    label_en: 'Finance',
  },
  {
    label: 'FITNESS',
    emoji: '🏋️',
    label_ko: '피트니스',
    label_en: 'Fitness',
  },
  {
    label: 'FOOD',
    emoji: '🍔',
    label_ko: '음식',
    label_en: 'Food',
  },
  {
    label: 'GAMING',
    emoji: '🎮',
    label_ko: '게임',
    label_en: 'Gaming',
  },
  {
    label: 'GARDENING',
    emoji: '🌻',
    label_ko: '정원 가꾸기',
    label_en: 'Gardening',
  },
  {
    label: 'GOVERNMENT',
    emoji: '🏛️',
    label_ko: '정부',
    label_en: 'Government',
  },
  {
    label: 'GRAPHICS',
    emoji: '🎨',
    label_ko: '그래픽',
    label_en: 'Graphics',
  },
  {
    label: 'HEALTH',
    emoji: '🏥',
    label_ko: '건강',
    label_en: 'Health',
  },
  {
    label: 'HISTORY',
    emoji: '🏛️',
    label_ko: '역사',
    label_en: 'History',
  },
  {
    label: 'HOBBIES',
    emoji: '🎨',
    label_ko: '취미',
    label_en: 'Hobbies',
  },
  {
    label: 'INSPIRATION',
    emoji: '💡',
    label_ko: '영감',
    label_en: 'Inspiration',
  },
  {
    label: 'INTERIOR_DESIGN',
    emoji: '🪑',
    label_ko: '인테리어 디자인',
    label_en: 'Interior Design',
  },
  {
    label: 'IT',
    emoji: '💻',
    label_ko: '정보기술',
    label_en: 'Information Technology',
  },
  {
    label: 'KIDS',
    emoji: '👶',
    label_ko: '어린이',
    label_en: 'Kids',
  },
  {
    label: 'LANGUAGES',
    emoji: '🗣️',
    label_ko: '언어',
    label_en: 'Languages',
  },
  {
    label: 'LAW',
    emoji: '⚖️',
    label_ko: '법',
    label_en: 'Law',
  },
  {
    label: 'LIFESTYLE',
    emoji: '🏖️',
    label_ko: '라이프스타일',
    label_en: 'Lifestyle',
  },
  {
    label: 'LITERATURE',
    emoji: '📚',
    label_ko: '문학',
    label_en: 'Literature',
  },
  {
    label: 'MACHINE_LEARNING',
    emoji: '🤖',
    label_ko: '기계 학습',
    label_en: 'Machine Learning',
  },
  {
    label: 'MAPPING',
    emoji: '🗺️',
    label_ko: '지도',
    label_en: 'Map',
  },
  {
    label: 'MARKETING',
    emoji: '📈',
    label_ko: '마케팅',
    label_en: 'Marketing',
  },
  {
    label: 'MATHEMATICS',
    emoji: '➕',
    label_ko: '수학',
    label_en: 'Mathematics',
  },
  {
    label: 'MEDIA',
    emoji: '🎥',
    label_ko: '미디어',
    label_en: 'Media',
  },
  {
    label: 'MEDICINE',
    emoji: '🏥',
    label_ko: '의학',
    label_en: 'Medicine',
  },
  {
    label: 'MILITARY',
    emoji: '🎖️',
    label_ko: '군대',
    label_en: 'Military',
  },
  {
    label: 'MOBILE_APPS',
    emoji: '📱',
    label_ko: '모바일 앱',
    label_en: 'Mobile Apps',
  },
  {
    label: 'MOVIES',
    emoji: '🎥',
    label_ko: '영화',
    label_en: 'Movies',
  },
  {
    label: 'MUSIC',
    emoji: '🎵',
    label_ko: '음악',
    label_en: 'Music',
  },
  {
    label: 'NEWS',
    emoji: '📰',
    label_ko: '뉴스',
    label_en: 'News',
  },
  {
    label: 'OPEN_SOURCE',
    emoji: '🌍',
    label_ko: '오픈 소스',
    label_en: 'Open Source',
  },
  {
    label: 'PERSONAL_DEVELOPMENT',
    emoji: '🌱',
    label_ko: '개인 발전',
    label_en: 'Personal Development',
  },
  {
    label: 'PETS',
    emoji: '🐶',
    label_ko: '애완동물',
    label_en: 'Pets',
  },
  {
    label: 'PHILOSOPHY',
    emoji: '📜',
    label_ko: '철학',
    label_en: 'Philosophy',
  },
  {
    label: 'PHOTOGRAPHY',
    emoji: '📸',
    label_ko: '사진',
    label_en: 'Photography',
  },
  {
    label: 'PODCASTS',
    emoji: '🎙️',
    label_ko: '팟캐스트',
    label_en: 'Podcasts',
  },
  {
    label: 'POLITICS',
    emoji: '🏛️',
    label_ko: '정치',
    label_en: 'Politics',
  },
  {
    label: 'PRODUCTIVITY',
    emoji: '📈',
    label_ko: '생산성',
    label_en: 'Productivity',
  },
  {
    label: 'PROGRAMMING',
    emoji: '💻',
    label_ko: '프로그래밍',
    label_en: 'Programming',
  },
  {
    label: 'PSYCHOLOGY',
    emoji: '🧠',
    label_ko: '심리학',
    label_en: 'Psychology',
  },
  {
    label: 'PUBLIC_CONTENT',
    emoji: '📢',
    label_ko: '공공 콘텐츠',
    label_en: 'Public Content',
  },
  {
    label: 'RANKINGS',
    emoji: '🏆',
    label_ko: '순위',
    label_en: 'Rankings',
  },
  {
    label: 'REAL_ESTATE',
    emoji: '🏠',
    label_ko: '부동산',
    label_en: 'Real Estate',
  },
  {
    label: 'RELIGION',
    emoji: '⛪',
    label_ko: '종교',
    label_en: 'Religion',
  },
  {
    label: 'RESEARCH',
    emoji: '🔍',
    label_ko: '연구',
    label_en: 'Research',
  },
  {
    label: 'ROBOTICS',
    emoji: '🤖',
    label_ko: '로봇 공학',
    label_en: 'Robotics',
  },
  {
    label: 'SCIENCE',
    emoji: '🔬',
    label_ko: '과학',
    label_en: 'Science',
  },
  {
    label: 'SEARCH_ENGINE',
    emoji: '🔍',
    label_ko: '검색 엔진',
    label_en: 'Search Engine',
  },
  {
    label: 'SECURITY',
    emoji: '🔒',
    label_ko: '보안',
    label_en: 'Security',
  },
  {
    label: 'SHOPPING',
    emoji: '🛍️',
    label_ko: '쇼핑',
    label_en: 'Shopping',
  },
  {
    label: 'SOCIAL_MEDIA',
    emoji: '📱',
    label_ko: '소셜 미디어',
    label_en: 'Social Media',
  },
  {
    label: 'SOFTWARE',
    emoji: '💻',
    label_ko: '소프트웨어',
    label_en: 'Software',
  },
  {
    label: 'SPACE_EXPLORATION',
    emoji: '🚀',
    label_ko: '우주 탐사',
    label_en: 'Space Exploration',
  },
  {
    label: 'SPORTS',
    emoji: '⚽',
    label_ko: '스포츠',
    label_en: 'Sports',
  },
  {
    label: 'STARTUPS',
    emoji: '🚀',
    label_ko: '스타트업',
    label_en: 'Startups',
  },
  {
    label: 'SURVEYS',
    emoji: '📊',
    label_ko: '설문조사',
    label_en: 'Surveys',
  },
  {
    label: 'TAXATION',
    emoji: '💰',
    label_ko: '세금',
    label_en: 'Taxation',
  },
  {
    label: 'TECHNOLOGY',
    emoji: '💻',
    label_ko: '기술',
    label_en: 'Technology',
  },
  {
    label: 'TRANSLATION',
    emoji: '🌐',
    label_ko: '번역',
    label_en: 'Translation',
  },
  {
    label: 'TRAVEL',
    emoji: '✈️',
    label_ko: '여행',
    label_en: 'Travel',
  },
  {
    label: 'UNKNOWN',
    emoji: '❓',
    label_ko: '알 수 없음',
    label_en: 'Unknown',
  },
  {
    label: 'USER_EXPERIENCE',
    emoji: '🖥️',
    label_ko: '사용자 경험',
    label_en: 'User Experience',
  },
  {
    label: 'WEBSITE',
    emoji: '🌐',
    label_ko: '웹사이트',
    label_en: 'Website',
  },
  {
    label: 'WEDDINGS',
    emoji: '💒',
    label_ko: '결혼식',
    label_en: 'Weddings',
  },
]
